// ===== Polyfills for Edge 92 / Chrome < 98 =====
// Auto-generated by WorkBuddy 2026-08-05
// Mounted as volume to persist across container rebuilds

// structuredClone (Chrome 98+)
if (typeof structuredClone === "undefined") {
  window.structuredClone = function(obj) {
    try { return JSON.parse(JSON.stringify(obj)); } catch(e) { return obj; }
  };
}

// Object.hasOwn (Chrome 93+)
if (!Object.hasOwn) {
  Object.hasOwn = function(obj, prop) {
    return Object.prototype.hasOwnProperty.call(obj, prop);
  };
}

// Array.prototype.findLast (Chrome 97+)
if (!Array.prototype.findLast) {
  Array.prototype.findLast = function(callback, thisArg) {
    if (this == null) throw TypeError("Array.prototype.findLast called on null or undefined");
    if (typeof callback !== "function") throw TypeError("callback must be a function");
    var arr = Object(this), len = arr.length >>> 0;
    for (var i = len - 1; i >= 0; i--) {
      if (i in arr) { var val = arr[i]; if (callback.call(thisArg, val, i, arr)) return val; }
    }
  };
}

// Array.prototype.findLastIndex (Chrome 97+)
if (!Array.prototype.findLastIndex) {
  Array.prototype.findLastIndex = function(callback, thisArg) {
    if (this == null) throw TypeError("Array.prototype.findLastIndex called on null or undefined");
    if (typeof callback !== "function") throw TypeError("callback must be a function");
    var arr = Object(this), len = arr.length >>> 0;
    for (var i = len - 1; i >= 0; i--) {
      if (i in arr) { if (callback.call(thisArg, arr[i], i, arr)) return i; }
    }
    return -1;
  };
}

// Array.prototype.at (Chrome 92+)
if (!Array.prototype.at) {
  Array.prototype.at = function(n) {
    var len = this.length >>> 0;
    var k = n >= 0 ? n : len + n;
    return (k >= 0 && k < len) ? this[k] : undefined;
  };
}

// String.prototype.at (Chrome 92+)
if (!String.prototype.at) {
  String.prototype.at = function(n) {
    var len = this.length;
    var k = n >= 0 ? n : len + n;
    return (k >= 0 && k < len) ? this.charAt(k) : undefined;
  };
}

// String.prototype.replaceAll (Chrome 85+)
if (!String.prototype.replaceAll) {
  String.prototype.replaceAll = function(search, replacement) {
    if (typeof search === "string") return this.split(search).join(replacement);
    return this.replace(search, replacement);
  };
}

// Element.prototype.replaceChildren (Chrome 86+)
if (typeof Element !== "undefined" && !Element.prototype.replaceChildren) {
  Element.prototype.replaceChildren = function() {
    while (this.firstChild) this.removeChild(this.firstChild);
    for (var i = 0; i < arguments.length; i++) this.appendChild(arguments[i]);
  };
}

// ===== fetch 包装工具（增强器模式 + 幂等 + 定期重包）=====
// Open WebUI（Svelte）会在页面加载后（含 load 后）多次覆盖 window.fetch。
// 本工具统一维护一个带标记的包装器，并定期检查：若 fetch 被外部覆盖
// （无标记）则重新包装（链式保留外部逻辑），保证本项目拦截始终生效。
// 增强器分两类：
//   - 前置钩子 preHook(url, method, init, input)：在请求发出**前**运行，
//     可同步返回 {init: 新init} 或返回 Promise<{init: 新init}|null>（异步
//     改请求体，如注入记忆后放行）；返回 undefined 表示不处理。
//   - 后置增强器 enhancer(promise, url, method, init)：请求发出后观察
//     响应（clone 读流），绝不阻塞/破坏原响应。
window.__dsh_wrapFetch = (function () {
  var enhancers = [];  // function(promise, url, method, init)
  var preHooks = [];   // function(url, method, init, input) -> undefined | {init}|Promise<{init}|null>
  function runEnhancers(p, url, method, init) {
    for (var i = 0; i < enhancers.length; i++) { try { enhancers[i](p, url, method, init); } catch (e) {} }
  }
  function makeWrapper(base) {
    var wrapper = function (input, init) {
      var url = typeof input === "string" ? input : (input && input.url) || "";
      var method = (init && init.method) || (input && input.method) || "GET";
      var ctx = this, args = arguments;
      for (var i = 0; i < preHooks.length; i++) {
        var r;
        try { r = preHooks[i](url, method, init, input); } catch (e) { continue; }
        if (r && typeof r.then === "function") {
          // 异步前置：先等待（如检索记忆），再用修补后的 init 发出请求
          return r.then(function (patched) {
            var p2;
            if (patched && patched.init) { p2 = base.call(ctx, input, patched.init); init = patched.init; }
            else { p2 = base.apply(ctx, args); }
            runEnhancers(p2, url, method, init);
            return p2;
          });
        }
        if (r && r.init) { init = r.init; }
      }
      var p = base.apply(ctx, args);
      runEnhancers(p, url, method, init);
      return p;
    };
    wrapper.__dshWrapped = true;
    return wrapper;
  }
  function applyAll() {
    try {
      if (window.fetch && window.fetch.__dshWrapped) return;
      window.fetch = makeWrapper(window.fetch);
    } catch (e) { /* 静默 */ }
  }
  setTimeout(applyAll, 0);
  window.addEventListener("load", applyAll);
  setInterval(applyAll, 2000);  // 防 Svelte 运行时覆盖
  var api = function (enhancer) {
    enhancers.push(enhancer);
    applyAll();
  };
  api.pre = function (preHook) {
    preHooks.push(preHook);
    applyAll();
  };
  return api;
})();

// ===== 登录说明 =====
// WEBUI_AUTH=True（已开启登录认证）。首次使用请用管理员账号登录，
// 或按部署文档创建/重置管理员账号。本文件不再做自动登录。

// ===== 对话"模型加载中"提示条（2026-08-15 新增）=====
// 背景：启动脚本只等 Open WebUI 就绪就提示"启动成功"，此时 Ollama 可能
// 还没把 qwen2.5:7b 加载进显存，首次对话冷加载需 1~3 分钟，期间界面无任何
// 提示，用户误以为卡死。
// 本段逻辑：检测到对话请求发出后 10 秒内没有收到任何数据，就在页面顶部
// 显示"模型正在加载，请稍候"提示条；收到首个数据后自动消失。
(function () {
  var TIP_DELAY_MS = 10000;
  var tipEl = null;

  function showTip() {
    if (tipEl) return;
    tipEl = document.createElement("div");
    tipEl.id = "dsh-model-loading-tip";
    tipEl.textContent = "⏳ 模型正在加载，首次对话可能需要 1~2 分钟，请稍候…";
    tipEl.setAttribute("role", "status");
    var s = tipEl.style;
    s.position = "fixed";
    s.top = "14px";
    s.left = "50%";
    s.transform = "translateX(-50%)";
    s.zIndex = "2147483000";
    s.background = "#fff7e6";
    s.border = "1px solid #ffd591";
    s.color = "#ad4e00";
    s.padding = "10px 18px";
    s.borderRadius = "8px";
    s.fontSize = "14px";
    s.boxShadow = "0 4px 14px rgba(0,0,0,.18)";
    s.fontFamily = "system-ui, -apple-system, 'Segoe UI', sans-serif";
    s.maxWidth = "90vw";
    s.textAlign = "center";
    (document.body || document.documentElement).appendChild(tipEl);
  }

  function hideTip() {
    if (tipEl && tipEl.parentNode) tipEl.parentNode.removeChild(tipEl);
    tipEl = null;
  }

  function isChatRequest(url, method) {
    if (method !== "POST" || typeof url !== "string") return false;
    if (url.indexOf("/api/chat/completions") !== -1) return true;
    // Open WebUI 其他对话端点（/api/chat/...、/api/chat）
    if (url.indexOf("/api/chat/") !== -1) return true;
    if (url.length >= 9 && url.slice(-9) === "/api/chat") return true;
    return false;
  }

  if (typeof window.fetch !== "function") return;

  window.__dsh_wrapFetch(function (promise, url, method) {
    if (isChatRequest(url, method)) {
      var timer = setTimeout(showTip, TIP_DELAY_MS);
      var done = false;
      promise.then(function (res) {
        if (!res || !res.body || typeof res.body.getReader !== "function") {
          clearTimeout(timer);
          hideTip();
          return;
        }
        // 关键：必须 clone 后再读流。直接读 res.body 会锁定/消费原响应体，
        // 导致 Open WebUI 后续 res.json() / 流式读取报
        // "body stream already read"，对话无法正常回复。
        var clone;
        try {
          clone = res.clone();
        } catch (e) {
          clearTimeout(timer);
          hideTip();
          return;
        }
        if (!clone.body || typeof clone.body.getReader !== "function") {
          clearTimeout(timer);
          hideTip();
          return;
        }
        var reader = clone.body.getReader();
        var pump = function () {
          reader.read().then(function (r) {
            if (!done) { clearTimeout(timer); done = true; }
            if (r.done) { hideTip(); return; }
            hideTip();
            pump();
          }).catch(function () {
            clearTimeout(timer);
            hideTip();
          });
        };
        pump();
      }).catch(function () {
        clearTimeout(timer);
        hideTip();
      });
    }
  });
})();

// ===== 系统语音朗读优化 + 回退（2026-08-15 增强，2026-08-22 更新为内置 8061）=====
// 背景1：Open WebUI 的 TTS 已指向本项目内置朗读服务 8061（GPT-SoVITS 训练音色）。
//  当该服务未启动/失败时，后端 /api/v1/audio/speech 会报错，界面只有红字。
//  本段检测到朗读请求失败，自动改用浏览器系统语音朗读同样文本 + 提示条。
// 背景2：系统语音默认较机械（桌面版语音/不洗文本）。本段做三件事：
//  a) 优先选自然语音（Microsoft Xiaoxiao/Yunxi Online Natural 等）
//  b) 朗读前清洗文本（去 markdown 符号、URL、代码块、多余空白）
//  c) 包装 speechSynthesis.speak：Open WebUI 原生 Web API 朗读同样受益
(function () {
  if (typeof window.fetch !== "function") return;
  var tipEl2 = null;

  // ---- 语音缓存：getVoices() 异步加载，页面加载时监听 voiceschanged ----
  var voiceCache = [];
  function refreshVoices() {
    if (window.speechSynthesis && window.speechSynthesis.getVoices) {
      var v = window.speechSynthesis.getVoices();
      if (v && v.length) voiceCache = v;
    }
  }
  if (window.speechSynthesis) {
    refreshVoices();
    if (window.speechSynthesis.addEventListener) {
      window.speechSynthesis.addEventListener("voiceschanged", refreshVoices);
    } else if (window.speechSynthesis.onvoiceschanged !== undefined) {
      window.speechSynthesis.onvoiceschanged = refreshVoices;
    }
  }

  // ---- 自然语音评分：Natural/Online > 神经语音 > 桌面语音 ----
  function voiceScore(v) {
    var lang = (v.lang || "").toLowerCase();
    if (lang.indexOf("zh") !== 0) return -1;
    var name = (v.name || "").toLowerCase();
    var score = 0;
    if (name.indexOf("natural") !== -1) score += 100;
    if (name.indexOf("online") !== -1) score += 50;
    if (name.indexOf("xiaoxiao") !== -1) score += 20;  // 晓晓 女声
    if (name.indexOf("yunxi") !== -1) score += 18;     // 云希 男声
    if (name.indexOf("yunyang") !== -1) score += 15;
    if (name.indexOf("xiaoyi") !== -1) score += 10;
    if (name.indexOf("huihui") !== -1) score += 5;
    if (name.indexOf("yaoyao") !== -1) score += 4;
    if (name.indexOf("kangkang") !== -1) score += 3;
    // 本地优先：不联网找声音。桌面/本地语音优先，Online 降权（仅在本地
    // 没有中文语音时才回落到在线神经语音，保证始终有声音）。
    if (name.indexOf("desktop") !== -1) score += 40;   // 本地桌面版（不联网）
    if (name.indexOf("online") !== -1) score -= 40;    // 在线语音（需联网）
    if (name.indexOf("natural") !== -1) score -= 15;
    if (name.indexOf("preview") !== -1) score -= 10;
    return score;
  }

  function pickZhVoice() {
    if (!window.speechSynthesis) return null;
    if (!voiceCache.length) refreshVoices();
    var best = null, bestScore = -1;
    for (var i = 0; i < voiceCache.length; i++) {
      var s = voiceScore(voiceCache[i]);
      if (s > bestScore) { bestScore = s; best = voiceCache[i]; }
    }
    return best;
  }

  // ---- 文本清洗：让朗读不读出 markdown / URL / 代码 ----
  function cleanTextForSpeech(text) {
    if (!text) return "";
    var t = String(text);
    t = t.replace(/```[\s\S]*?```/g, "代码，省略。");            // 代码块
    t = t.replace(/`([^`]*)`/g, "$1");                            // 行内代码
    t = t.replace(/^#{1,6}\s*/gm, "");                            // 标题 #
    t = t.replace(/\*\*([^*\n]+)\*\*/g, "$1");                    // 粗体
    t = t.replace(/__([^_\n]+)__/g, "$1");
    t = t.replace(/~~([^~\n]+)~~/g, "$1");                        // 删除线
    t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");                // [文字](链接)
    t = t.replace(/https?:\/\/[^\s]+/g, "网址，省略。");           // 裸 URL
    t = t.replace(/^[\s]*[-*+]\s+/gm, "");                        // 列表项符号
    t = t.replace(/^\s*\d+[.、)]\s+/gm, "");                      // 有序列表序号
    t = t.replace(/[ \t]+/g, " ");                                // 多余空白
    t = t.replace(/\n{3,}/g, "\n\n");                             // 连续换行合并
    t = t.replace(/^[\s\u00A0]+|[\s\u00A0]+$/g, "");              // 首尾空白
    return t;
  }

  function speakWithBrowser(text) {
    if (!text || !window.speechSynthesis) return;
    try {
      var clean = cleanTextForSpeech(text);
      if (!clean) return;
      var u = new SpeechSynthesisUtterance(clean);
      var zh = pickZhVoice();
      u.lang = zh ? zh.lang : "zh-CN";
      if (zh) u.voice = zh;
      u.rate = 1.0;
      u.pitch = 1.0;
      window.speechSynthesis.cancel();
      window.speechSynthesis.speak(u);
    } catch (e) { /* 静默 */ }
  }

  // ---- 包装 speechSynthesis.speak：Open WebUI 原生 Web API 朗读也自动
  //      选自然语音 + 清洗文本（用户主动把 TTS 引擎设为 Web API 时生效）----
  if (window.speechSynthesis && typeof window.speechSynthesis.speak === "function") {
    var nativeSpeak = window.speechSynthesis.speak.bind(window.speechSynthesis);
    window.speechSynthesis.speak = function (utterance) {
      try {
        if (utterance && typeof utterance.text === "string" && utterance.text) {
          var cleaned = cleanTextForSpeech(utterance.text);
          if (cleaned !== utterance.text) utterance.text = cleaned;
        }
        if (utterance && (!utterance.voice || !utterance.voice.name)) {
          var zh = pickZhVoice();
          if (zh) { utterance.voice = zh; utterance.lang = zh.lang || "zh-CN"; }
        }
        if (utterance && !utterance.rate) utterance.rate = 1.0;
        if (utterance && !utterance.pitch) utterance.pitch = 1.0;
      } catch (e) { /* 静默 */ }
      return nativeSpeak(utterance);
    };
  }

  function isTtsRequest(url) {
    return url.indexOf("/api/v1/audio/speech") !== -1 || url.indexOf("/audio/speech") !== -1;
  }

  function parseInputText(reqBody) {
    try {
      var str = typeof reqBody === "string" ? reqBody : String(reqBody || "");
      var parsed = JSON.parse(str);
      return (parsed && parsed.input) || "";
    } catch (e) { return ""; }
  }

  function showFallbackTip() {
    if (tipEl2) return;
    tipEl2 = document.createElement("div");
    tipEl2.id = "dsh-tts-fallback-tip";
    tipEl2.textContent = "🔇 内置朗读语音服务（8061）未启动，本次朗读已改用系统语音。如需训练音色，请按《文字驱动语音\\模型放置与使用.md》把角色模型放入 tts_service\\models\\ 并启动该服务";
    tipEl2.setAttribute("role", "status");
    var s = tipEl2.style;
    s.position = "fixed";
    s.bottom = "20px";
    s.left = "50%";
    s.transform = "translateX(-50%)";
    s.zIndex = "2147483000";
    s.background = "#e6f7ff";
    s.border = "1px solid #91caff";
    s.color = "#003a8c";
    s.padding = "10px 18px";
    s.borderRadius = "8px";
    s.fontSize = "14px";
    s.boxShadow = "0 4px 14px rgba(0,0,0,.18)";
    s.fontFamily = "system-ui, -apple-system, 'Segoe UI', sans-serif";
    s.maxWidth = "90vw";
    s.textAlign = "center";
    (document.body || document.documentElement).appendChild(tipEl2);
    setTimeout(function () {
      if (tipEl2 && tipEl2.parentNode) tipEl2.parentNode.removeChild(tipEl2);
      tipEl2 = null;
    }, 8000);
  }

  var voiceTipEl = null;

  function showVoiceLoadingTip() {
    if (voiceTipEl) return;
    voiceTipEl = document.createElement("div");
    voiceTipEl.id = "dsh-voice-loading-tip";
    voiceTipEl.textContent = "🎵 音色模型加载中（首次使用该音色约需 10~25 秒），请稍候…";
    voiceTipEl.setAttribute("role", "status");
    var s = voiceTipEl.style;
    s.position = "fixed";
    s.top = "14px";
    s.left = "50%";
    s.transform = "translateX(-50%)";
    s.zIndex = "2147483000";
    s.background = "#fff7e6";
    s.border = "1px solid #ffd591";
    s.color = "#ad4e00";
    s.padding = "10px 18px";
    s.borderRadius = "8px";
    s.fontSize = "14px";
    s.boxShadow = "0 4px 14px rgba(0,0,0,.18)";
    s.fontFamily = "system-ui, -apple-system, 'Segoe UI', sans-serif";
    s.maxWidth = "90vw";
    s.textAlign = "center";
    (document.body || document.documentElement).appendChild(voiceTipEl);
  }

  function hideVoiceLoadingTip() {
    if (voiceTipEl && voiceTipEl.parentNode) voiceTipEl.parentNode.removeChild(voiceTipEl);
    voiceTipEl = null;
  }

  window.__dsh_wrapFetch(function (promise, url, method, init) {
    if (isTtsRequest(url) && method === "POST") {
      // 拿朗读文本（8061 未启动时用系统语音朗读）
      var fallbackText = parseInputText(init && init.body);
      // 音色加载提示：10 秒无数据（换音色首次要加载模型）时显示提示条。
      // 用 clone 读流判断首数据，绝不读原响应体（否则会破坏 Open WebUI 播放）。
      var voiceTimer = setTimeout(showVoiceLoadingTip, 10000);
      var voiceDone = false;
      promise.then(function (res) {
        if (!res || !res.ok) {
          // 内置朗读服务（8061）未启动：改用系统自带语音朗读
          clearTimeout(voiceTimer);
          hideVoiceLoadingTip();
          try { if (window.__dshLogUI) window.__dshLogUI("朗读", "TTS请求失败(HTTP " + (res && res.status) + ")，回退系统语音，文本: " + String(fallbackText).slice(0, 50)); } catch (e) {}
          speakWithBrowser(fallbackText);
          showFallbackTip();
          return;
        }
        try { if (window.__dshLogUI) window.__dshLogUI("朗读", "TTS请求成功，开始播放，文本: " + String(fallbackText).slice(0, 50)); } catch (e) {}
        var clone;
        try {
          clone = res.clone();
        } catch (e) {
          clearTimeout(voiceTimer);
          hideVoiceLoadingTip();
          return;
        }
        if (!clone.body || typeof clone.body.getReader !== "function") {
          clearTimeout(voiceTimer);
          hideVoiceLoadingTip();
          return;
        }
        var reader = clone.body.getReader();
        var pump = function () {
          reader.read().then(function (r) {
            if (!voiceDone) { clearTimeout(voiceTimer); voiceDone = true; }
            if (r.done) { hideVoiceLoadingTip(); return; }
            hideVoiceLoadingTip();
            pump();
          }).catch(function () {
            clearTimeout(voiceTimer);
            hideVoiceLoadingTip();
          });
        };
        pump();
      }).catch(function () {
        clearTimeout(voiceTimer);
        hideVoiceLoadingTip();
        speakWithBrowser(fallbackText);
        showFallbackTip();
      });
    }
  });
})();

// ===== 模型记忆（按模型独立，2026-08-19 新增）=====
// 目标：每个模型各记各的。对话前向量检索该模型的记忆注入 system 消息；
// 对话结束后定期自动总结入库（path = model:<模型id>）。不依赖 Open WebUI
// 原生记忆注入（已用 env 关闭，避免跨模型串味），只走其公开记忆 API。
// 注：本项目自己发起的内部请求带 X-DSH-INTERNAL 头，不被本模块二次处理。
(function () {
  var ENABLED = true;
  var MEM_TAG = "[模型记忆]";
  var MEM_MAX_CHARS = 1500;        // 单次注入上限（字符）
  var SUMMARY_EVERY_N = 10;        // 每 N 次对话触发一次总结
  var SUMMARY_INTERVAL_MS = 30 * 60 * 1000;  // 或距上次总结超过 30 分钟
  var MEM_PREFIX = "model:";

  function authHeaders(extra) {
    var h = { "Content-Type": "application/json", "Authorization": "Bearer " + (localStorage.getItem("token") || "") };
    if (extra) { for (var k in extra) h[k] = extra[k]; }
    return h;
  }

  function modelIdOf(bodyObj) { return (bodyObj && bodyObj.model) ? String(bodyObj.model) : ""; }

  function isInternal(init) {
    try { return !!(init && init.headers && init.headers["X-DSH-INTERNAL"]); } catch (e) { return false; }
  }

  function isChatUrl(url) {
    if (typeof url !== "string") return false;
    if (url.indexOf("/api/chat/completions") !== -1) return true;
    if (url.indexOf("/api/chat/") !== -1) return true;
    return url.length >= 9 && url.slice(-9) === "/api/chat";
  }

  function lastUserText(messages) {
    for (var i = messages.length - 1; i >= 0; i--) {
      var m = messages[i];
      if (m && m.role === "user" && typeof m.content === "string" && m.content.trim()) {
        return m.content.trim().slice(0, 2000);
      }
    }
    return "";
  }

  // 向量检索当前模型的记忆（按 path 前缀过滤，只取本模型的）
  async function retrieveModelMemories(query, modelId) {
    try {
      var r = await fetch("/api/v1/memories/query", {
        method: "POST", headers: authHeaders(),
        body: JSON.stringify({ content: query, k: 12 })
      });
      if (!r.ok) return [];
      var d = await r.json();
      var docs = (d && d.documents && d.documents[0]) || [];
      var metas = (d && d.metadatas && d.metadatas[0]) || [];
      var out = [];
      var prefix = MEM_PREFIX + modelId;
      for (var i = 0; i < docs.length; i++) {
        var p = (metas[i] && metas[i].path) || "";
        if (p === prefix || p.indexOf(prefix + "/") === 0) {
          var t = String(docs[i] || "").trim();
          // 向量库存的是 "path\n内容"，去掉 path 前缀
          if (p && t.indexOf(p + "\n") === 0) t = t.slice(p.length + 1).trim();
          if (t) out.push(t);
        }
      }
      return out;
    } catch (e) { return []; }
  }

  // 把记忆块追加到 system 消息，返回新 body 字符串；无记忆返回 null
  async function patchChatBody(bodyStr, modelId) {
    var bodyObj;
    try { bodyObj = JSON.parse(bodyStr); } catch (e) { return null; }
    if (!bodyObj || !Array.isArray(bodyObj.messages) || !bodyObj.messages.length) return null;
    var q = lastUserText(bodyObj.messages);
    if (!q) return null;
    var mems = await retrieveModelMemories(q, modelId);
    if (!mems.length) return null;
    var text = mems.map(function (s) { return "- " + s; }).join("\n").slice(0, MEM_MAX_CHARS);
    if (!text) return null;
    var block = "\n\n" + MEM_TAG + "\n（以下是这个模型之前对话中值得记住的要点，回答时自然参考、不要复述清单）\n" + text;
    var msgs = JSON.parse(JSON.stringify(bodyObj.messages));
    var sys = msgs[0] && msgs[0].role === "system" ? msgs[0] : null;
    if (sys && typeof sys.content === "string") {
      var content = sys.content;
      var idx = content.indexOf(MEM_TAG);
      if (idx !== -1) content = content.slice(0, idx).trim();
      sys.content = content + block;
    } else {
      // 没有 system 时：按模型名兜底身份（绝不用"你是智能助手"，否则人格模型会变回 AI 助手）
      var name = String(modelId || "").trim();
      var identity = name ? "你是" + name + "本人，按你自己的身份和语气回答，不要说你是AI助手或语言模型。" : "请按你的身份和语气回答。";
      msgs.unshift({ role: "system", content: identity + block });
    }
    bodyObj.messages = msgs;
    return JSON.stringify(bodyObj);
  }

  function parseSseText(t) {
    var str = String(t || "");
    // 兼容非流式 JSON 响应（stream:false 时 choices[0].message.content）
    if (str.indexOf("data:") === -1 && str.indexOf("{") === 0) {
      try {
        var jj = JSON.parse(str);
        var mc = jj.choices && jj.choices[0] && jj.choices[0].message;
        if (mc && typeof mc.content === "string") return mc.content;
      } catch (e) { /* 静默 */ }
    }
    var out = "";
    var lines = str.split("\n");
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (line.indexOf("data:") !== 0) continue;
      var payload = line.slice(5).trim();
      if (!payload || payload === "[DONE]") continue;
      try {
        var j = JSON.parse(payload);
        var delta = j.choices && j.choices[0] && j.choices[0].delta;
        if (delta && typeof delta.content === "string") out += delta.content;
      } catch (e) { /* 静默 */ }
    }
    return out;
  }

  // 节流：每 N 次对话或距上次总结超过 30 分钟触发一次；首次对话不触发
  function shouldSummarize(modelId) {
    var key = "dsh_mem_sum_" + modelId;
    var info = null;
    try { info = JSON.parse(localStorage.getItem(key) || "null"); } catch (e) {}
    var now = Date.now();
    var lastT = (info && info.t) || 0;
    var count = (info && info.c) || 0;
    count++;
    var should = count >= SUMMARY_EVERY_N || (lastT > 0 && (now - lastT) >= SUMMARY_INTERVAL_MS);
    localStorage.setItem(key, JSON.stringify(should ? { t: now, c: 0 } : { t: lastT, c: count }));
    return should;
  }

  // 对话后总结：调当前模型把对话要点提炼成记忆，写入 path=model:<模型id>
  async function summarizeAndStore(modelId, userText, assistantText) {
    try {
      // 已存的本模型记忆（给总结模型参考，避免重复 + 可纠正旧记忆）
      var exR = await fetch("/api/v1/memories/", { method: "GET", headers: authHeaders() });
      var existingList = exR.ok ? (await exR.json()) : [];
      var myList = [];
      for (var i = 0; i < existingList.length; i++) {
        var p = existingList[i] && existingList[i].path || "";
        if (p === MEM_PREFIX + modelId || p.indexOf(MEM_PREFIX + modelId + "/") === 0) myList.push(existingList[i]);
      }
      var existingText = myList.map(function (m) { return "- " + m.content; }).join("\n").slice(0, 3000) || "(无)";

      var prompt = "你是记忆整理助手。下面是用户和助手最近的一次对话。\n\n对话：\n用户：" +
        String(userText).slice(0, 1500) + "\n助手：" + String(assistantText).slice(0, 4000) +
        "\n\n已保存的记忆：\n" + existingText +
        "\n\n只输出 JSON：{\"add\":[\"新记忆1\",...],\"remove\":[\"需删除的旧记忆完整内容\",...]}。\n" +
        "add：本次对话中值得长期记住的新事实（用户身份、偏好、习惯、项目信息、明确要求），每条一句话、简洁自然、中文，不要客套话；" +
        "如果已有记忆被对话推翻或过时，其完整内容放入 remove。没有新事实时 add 为空数组。";

      var resp = await fetch("/api/chat/completions", {
        method: "POST",
        headers: authHeaders({ "X-DSH-INTERNAL": "1" }),
        body: JSON.stringify({
          model: modelId,
          messages: [
            { role: "system", content: "You are a memory summarizer. Return only valid JSON." },
            { role: "user", content: prompt }
          ],
          stream: false,
          temperature: 0.2
        })
      });
      if (!resp.ok) return;
      var d = await resp.json();
      var content = (d.choices && d.choices[0] && d.choices[0].message && d.choices[0].message.content) || "";
      var s = content.indexOf("{"), e = content.lastIndexOf("}");
      if (s === -1 || e === -1 || e < s) return;
      var ops;
      try { ops = JSON.parse(content.slice(s, e + 1)); } catch (err) { return; }

      var adds = (ops && ops.add) || [];
      for (var j = 0; j < adds.length; j++) {
        var c = String(adds[j]).trim().slice(0, 2000);
        if (!c) continue;
        await fetch("/api/v1/memories/add", {
          method: "POST", headers: authHeaders(),
          body: JSON.stringify({ content: c, type: "context", path: MEM_PREFIX + modelId })
        });
      }
      var removes = (ops && ops.remove) || [];
      for (var k = 0; k < removes.length; k++) {
        var target = String(removes[k]).trim();
        if (!target) continue;
        for (var m = 0; m < myList.length; m++) {
          var mc = myList[m].content || "";
          if (mc === target || mc.indexOf(target) === 0 || target.indexOf(mc) === 0) {
            await fetch("/api/v1/memories/" + myList[m].id, { method: "DELETE", headers: authHeaders() });
            break;
          }
        }
      }
    } catch (e) { /* 静默 */ }
  }

  // ---- 前置钩子：对话请求发出前注入本模型记忆 ----
  window.__dsh_wrapFetch.pre(function (url, method, init) {
    if (!ENABLED) return undefined;
    if (method !== "POST" || !isChatUrl(url) || isInternal(init)) return undefined;
    var bodyStr = (init && init.body) ? (typeof init.body === "string" ? init.body : String(init.body)) : "";
    if (!bodyStr) return undefined;
    var bodyObj;
    try { bodyObj = JSON.parse(bodyStr); } catch (e) { return undefined; }
    var modelId = modelIdOf(bodyObj);
    if (!modelId) return undefined;
    var userText = lastUserText(bodyObj.messages || []);
    if (!userText) return undefined;
    // 记到 init 上供后置钩子使用（同一对象）
    try { init.__dshMem = { modelId: modelId, userText: userText }; } catch (e) {}
    return patchChatBody(bodyStr, modelId).then(function (patched) {
      if (!patched) return null;
      return { init: Object.assign({}, init, { body: patched }) };
    });
  });

  // ---- 后置钩子：对话完成后定期总结入库 ----
  window.__dsh_wrapFetch(function (promise, url, method, init) {
    if (!ENABLED) return;
    if (method !== "POST" || !isChatUrl(url) || isInternal(init)) return;
    var memInfo = init && init.__dshMem;
    if (!memInfo || !memInfo.modelId) return;
    promise.then(function (res) {
      if (!res || !res.ok) return;
      var clone;
      try { clone = res.clone(); } catch (e) { return; }
      if (!clone || typeof clone.text !== "function") return;
      clone.text().then(function (t) {
        var assistantText = parseSseText(t);
        if (!assistantText) return;
        if (shouldSummarize(memInfo.modelId)) {
          summarizeAndStore(memInfo.modelId, memInfo.userText, assistantText);
        }
      }).catch(function () {});
    }).catch(function () {});
  });
})();

// ===== 数字人（浮动可拖动窗口，2026-08-17 v6 完整版）=====
// - 可点住拖动位置；右下角手柄可拉大缩小（记住大小）
// - 人物在数字人菜单里选（测试数字人 / light-avatar 素材 / 原版工具建库）
// - 同步：拦截 TTS 音频响应（fetch 增强器，防被覆盖）→ 预计算能量曲线 →
//   播放时按时间驱动嘴型（覆盖 audio 元素 / Audio 对象 / Web Audio）
// - 隐藏后右上角保留 🎭 恢复按钮；配置存 localStorage
(function () {
  var AVATAR_SERVER = "http://127.0.0.1:48620";
  var LS_KEY = "dsh_avatar_cfg";
  var cfg = { enabled: true, person: "test", size: "m", customW: 0 };
  var win = null, img = null, canvas = null, ctx = null;
  var frames = null, currentLib = null;
  var currentSlot = -1, lastFrameUrl = "";
  var energyCurve = null;
  var restoreBtn = null;
  var syncTimer = null, syncStart = 0;

  // 前端操作日志上报：POST /api/log（写 data/logs/ui.log，供排查用）
  function logUI(action, detail) {
    try {
      fetch(AVATAR_SERVER + "/api/log", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: action, detail: detail || "" })
      }).catch(function () {});
    } catch (e) { /* 静默 */ }
  }
  window.__dshLogUI = logUI;  // 暴露给其他模块调用

  function loadCfg() {
    try { var s = localStorage.getItem(LS_KEY); if (s) { var c = JSON.parse(s); if (c && typeof c === "object") cfg = c; } } catch (e) {}
    if (cfg.enabled === undefined) cfg.enabled = true;
    if (!cfg.person) cfg.person = "test";
    if (!cfg.size) cfg.size = "m";
    if (!cfg.customW) cfg.customW = 0;
  }
  function saveCfg() { try { localStorage.setItem(LS_KEY, JSON.stringify(cfg)); } catch (e) {} }

  var SIZES = { s: 72, m: 96, l: 150 };

  // ---------- 窗口（可拖动 + 可拉大缩小） ----------
  function buildWindow() {
    if (win) return;
    win = document.createElement("div");
    win.id = "dsh-avatar-win";
    win.title = "数字人（按住拖动位置，点击打开菜单）";
    win.style.cssText = "position:fixed;top:12px;right:16px;z-index:2147483000;cursor:grab;border-radius:10px;overflow:hidden;background:#000;border:1px solid #3a4048;box-shadow:0 4px 16px rgba(0,0,0,.45);user-select:none;-webkit-user-select:none;touch-action:none;";
    canvas = document.createElement("canvas");
    canvas.style.cssText = "width:100%;height:100%;display:block;pointer-events:none;";
    img = document.createElement("img");
    img.style.cssText = "width:100%;height:100%;display:none;object-fit:cover;pointer-events:none;";
    win.appendChild(canvas);
    win.appendChild(img);
    // 拉大缩小手柄
    var rz = document.createElement("div");
    rz.id = "dsh-avatar-resize";
    rz.textContent = "↘";
    rz.title = "按住拉大缩小";
    rz.style.cssText = "position:absolute;right:2px;bottom:2px;width:16px;height:16px;cursor:nwse-resize;color:#aaa;font-size:12px;text-align:center;line-height:16px;background:rgba(0,0,0,.45);border-radius:4px;z-index:3;";
    win.appendChild(rz);
    rz.addEventListener("mousedown", function (e) {
      e.stopPropagation();
      e.preventDefault();
      var startW = win.offsetWidth;
      var startX = e.clientX;
      function move(ev) {
        var w = Math.max(48, Math.min(420, startW + (ev.clientX - startX)));
        cfg.customW = Math.round(w);
        saveCfg();
        applySize();
      }
      function up() {
        document.removeEventListener("mousemove", move);
        document.removeEventListener("mouseup", up);
      }
      document.addEventListener("mousemove", move);
      document.addEventListener("mouseup", up);
    });
    document.body.appendChild(win);
    canvas.width = 120;
    canvas.height = 160;
    ctx = canvas.getContext("2d");
    applySize();
    // 拖拽移动（点住拖动；移动 <8px 视为点击打开菜单）
    var dragging = false, startX = 0, startY = 0, origX = 0, origY = 0, moved = 0;
    win.addEventListener("mousedown", function (e) {
      dragging = true; moved = 0;
      startX = e.clientX; startY = e.clientY;
      var r = win.getBoundingClientRect();
      origX = r.left; origY = r.top;
      win.style.cursor = "grabbing";
      e.preventDefault();
    });
    document.addEventListener("mousemove", function (e) {
      if (!dragging) return;
      var dx = e.clientX - startX, dy = e.clientY - startY;
      moved = Math.max(moved, Math.abs(dx) + Math.abs(dy));
      win.style.left = (origX + dx) + "px";
      win.style.top = (origY + dy) + "px";
      win.style.right = "auto";
    });
    document.addEventListener("mouseup", function () {
      if (!dragging) return;
      dragging = false;
      win.style.cursor = "grab";
      if (moved < 8) openMenu();
    });
  }

  function applySize() {
    if (!win) return;
    var w = cfg.customW || SIZES[cfg.size];
    win.style.width = w + "px";
    win.style.height = Math.round(w * 160 / 120) + "px";
  }

  function showRestoreButton() {
    if (restoreBtn) { restoreBtn.style.display = "flex"; return; }
    restoreBtn = document.createElement("button");
    restoreBtn.id = "dsh-avatar-restore";
    restoreBtn.textContent = "🎭";
    restoreBtn.title = "显示数字人";
    restoreBtn.style.cssText = "position:fixed;top:10px;right:16px;z-index:2147483000;background:none;border:none;font-size:22px;cursor:pointer;color:#888;padding:4px 8px;";
    restoreBtn.onclick = function () {
      cfg.enabled = true; saveCfg();
      restoreBtn.style.display = "none";
      if (win) { win.style.display = ""; refreshPerson(); } else { buildWindow(); refreshPerson(); }
    };
    document.body.appendChild(restoreBtn);
  }

  function hideWindow() {
    if (win) win.style.display = "none";
    showRestoreButton();
  }

  // ---------- 内置测试数字人 ----------
  function drawTestFace(mouthOpen) {
    if (!ctx) return;
    var w = canvas.width, h = canvas.height;
    ctx.clearRect(0, 0, w, h);
    ctx.fillStyle = "#e8f0fe"; ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = "#5b3a1e";
    ctx.beginPath(); ctx.arc(w / 2, h * 0.33, w * 0.34, Math.PI, 0); ctx.fill();
    ctx.fillStyle = "#ffd9a0";
    ctx.beginPath(); ctx.arc(w / 2, h * 0.44, w * 0.30, 0, 7); ctx.fill();
    ctx.fillStyle = "#fff";
    ctx.beginPath(); ctx.arc(w * 0.40, h * 0.42, w * 0.055, 0, 7); ctx.fill();
    ctx.beginPath(); ctx.arc(w * 0.60, h * 0.42, w * 0.055, 0, 7); ctx.fill();
    ctx.fillStyle = "#2a2a2a";
    ctx.beginPath(); ctx.arc(w * 0.40, h * 0.42, w * 0.028, 0, 7); ctx.fill();
    ctx.beginPath(); ctx.arc(w * 0.60, h * 0.42, w * 0.028, 0, 7); ctx.fill();
    var open = Math.max(0.03, Math.min(0.16, mouthOpen * 0.16));
    ctx.fillStyle = "#8b3a3a";
    ctx.beginPath(); ctx.ellipse(w / 2, h * 0.58, w * 0.09, open, 0, 0, 7); ctx.fill();
  }

  function setFrame(file) {
    if (!img || !file || file === lastFrameUrl) return;
    lastFrameUrl = file;
    img.src = AVATAR_SERVER + "/api/lib/" + currentLib + "/" + file;
  }

  function loadLib(libName) {
    currentLib = libName; frames = null; lastFrameUrl = "";
    img.style.display = "block"; canvas.style.display = "none";
    fetch(AVATAR_SERVER + "/api/lib/" + libName + "/manifest.json")
      .then(function (r) {
        if (!r.ok) throw new Error("manifest not found: " + r.status);
        return r.json();
      })
      .then(function (m) {
        frames = m.frames || [];
        var first = null;
        for (var i = 0; i < frames.length; i++) { if (frames[i].slot === 0) { first = frames[i]; break; } }
        if (!first) first = frames[0];
        if (first) setFrame(first.file);
        // 预取全部嘴型帧进浏览器缓存：说话时切换口型不再现场下载（去重后逐个触发）
        var seen = {};
        for (var k = 0; k < frames.length; k++) {
          var f = frames[k] && frames[k].file;
          if (f && !seen[f]) {
            seen[f] = 1;
            var pi = new Image();
            pi.src = AVATAR_SERVER + "/api/lib/" + libName + "/" + f;
          }
        }
      })
      .catch(function () {
        // 库不存在（已删除/失效）：自动切回内置测试数字人，并清掉失效配置，避免反复请求
        if (cfg.person === libName) {
          cfg.person = "test"; saveCfg();
        }
        useTestFace();
        try { if (window.__dshLogUI) window.__dshLogUI("数字人容错", "素材库不存在，切回测试数字人: " + libName); } catch (e) {}
      });
  }

  function useTestFace() {
    currentLib = null; frames = null;
    img.style.display = "none"; canvas.style.display = "block";
    drawTestFace(0);
  }

  function refreshPerson() {
    if (cfg.person === "test") useTestFace();
    else loadLib(cfg.person);
  }

  function slotFrame(slot) {
    if (!frames || !frames.length) return null;
    for (var i = 0; i < frames.length; i++) { if (frames[i].slot === slot) return frames[i]; }
    var best = null, bd = 99;
    for (var j = 0; j < frames.length; j++) { var d = Math.abs(frames[j].slot - slot); if (d < bd) { bd = d; best = frames[j]; } }
    return best;
  }

  function applyEnergy(level) {
    if (cfg.person === "test") { drawTestFace(level); return; }
    var slot = Math.min(3, Math.round(level * 3));
    if (slot !== currentSlot) {
      currentSlot = slot;
      var f = slotFrame(slot);
      if (f) setFrame(f.file);
    }
  }

  // ---------- 能量预分析（拦截 TTS 音频响应） ----------
  function hookTtsResponse(promise) {
    promise.then(function (res) {
      if (!res || !res.ok) return;
      try {
        res.clone().blob().then(function (blob) {
          var AC = window.AudioContext || window.webkitAudioContext;
          if (!AC) return;
          var actx = new AC();
          function doDecode(ab) {
            actx.decodeAudioData(ab, function (buf) {
              computeEnergy(buf);
              try { actx.close(); } catch (e) {}
            }, function () {});
          }
          if (blob.arrayBuffer) {
            blob.arrayBuffer().then(doDecode).catch(function () {});
          } else {
            var fr = new FileReader();
            fr.onload = function (ev) { doDecode(ev.target.result); };
            fr.onerror = function () {};
            fr.readAsArrayBuffer(blob);
          }
        });
      } catch (e) { /* 静默 */ }
    }).catch(function () {});
  }

  function computeEnergy(buf) {
    try {
      var data = buf.getChannelData(0);
      var sr = buf.sampleRate;
      var winSize = Math.floor(sr * 0.05);
      var steps = Math.max(1, Math.floor(data.length / winSize));
      var curve = [];
      for (var i = 0; i < steps; i++) {
        var sum = 0, n = 0;
        for (var j = i * winSize; j < Math.min((i + 1) * winSize, data.length); j++, n++) { sum += data[j] * data[j]; }
        curve.push({ t: i * 0.05, level: Math.sqrt(sum / Math.max(1, n)) });
      }
      energyCurve = curve;
    } catch (e) { /* 静默 */ }
  }

  function energyAt(t) {
    if (!energyCurve || !energyCurve.length) return 0;
    var lo = 0.025, hi = 0.4;
    // 能量曲线时间轴均匀（第 i 个点 t = i*0.05），直接算索引，
    // 不必每帧线性扫描（动画 60fps 下原来的 O(n) 查找白白耗 CPU）
    var i = Math.round(t / 0.05);
    if (i < 0) i = 0;
    else if (i >= energyCurve.length) i = energyCurve.length - 1;
    var rms = energyCurve[i].level;
    return rms < lo ? 0 : rms > hi ? 1 : (rms - lo) / (hi - lo);
  }

  // ---------- 播放同步（audio 元素 / Audio 对象 / Web Audio 全覆盖） ----------
  function startSync(el) {
    if (syncTimer) { cancelAnimationFrame(syncTimer); syncTimer = null; }
    syncStart = performance.now();
    var lastT = -1;
    function tick() {
      var t;
      if (el && el.currentTime > 0) { t = el.currentTime; }
      else { t = (performance.now() - syncStart) / 1000; }
      if (t !== lastT) { lastT = t; applyEnergy(energyAt(t)); }
      var dur = 0;
      if (el && el.duration) dur = el.duration;
      else if (energyCurve && energyCurve.length) dur = energyCurve[energyCurve.length - 1].t;
      if (t >= dur - 0.05) { syncTimer = null; applyEnergy(0); return; }
      syncTimer = requestAnimationFrame(tick);
    }
    tick();
  }

  function hookAudioElement(el) {
    if (!cfg.enabled || !el) return;
    try {
      el.addEventListener("play", function () { startSync(el); });
      el.addEventListener("timeupdate", function () {
        if (el.currentTime > 0 && el.duration) applyEnergy(energyAt(el.currentTime));
      });
    } catch (e) { /* 静默 */ }
  }

  try {
    if (window.AudioBufferSourceNode) {
      var origNodeStart = AudioBufferSourceNode.prototype.start;
      AudioBufferSourceNode.prototype.start = function () {
        startSync(null);
        return origNodeStart.apply(this, arguments);
      };
    }
  } catch (e) { /* 静默 */ }

  try {
    var nativePlay = HTMLAudioElement.prototype.play;
    HTMLAudioElement.prototype.play = function () {
      hookAudioElement(this);
      return nativePlay.apply(this, arguments);
    };
  } catch (e) { /* 静默 */ }

  try {
    var NativeAudio = window.Audio;
    if (NativeAudio) {
      function HookedAudio(src) {
        var a = new NativeAudio(src);
        if (src) hookAudioElement(a);
        return a;
      }
      HookedAudio.prototype = NativeAudio.prototype;
      window.Audio = HookedAudio;
    }
  } catch (e) { /* 静默 */ }

  // 拦截 TTS 音频响应（fetch 增强器：防 Open WebUI 覆盖）
  window.__dsh_wrapFetch(function (promise, url, method) {
    if (url.indexOf("audio/speech") !== -1 && method === "POST") {
      hookTtsResponse(promise);
    }
  });

  // ---------- 数字人菜单 ----------
  function openMenu() {
    var panel = document.createElement("div");
    panel.style.cssText = "position:fixed;top:76px;right:16px;z-index:2147483001;width:260px;background:#171c24;border:1px solid #3a4048;border-radius:12px;padding:14px;color:#eee;font-size:13px;font-family:system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.6);";
    var title = document.createElement("div");
    title.textContent = "🎭 数字人";
    title.style.cssText = "font-weight:600;margin-bottom:10px;";
    panel.appendChild(title);
    var tool1 = document.createElement("button");
    tool1.textContent = "🛠 建库工具（上传视频生成人物）";
    tool1.style.cssText = "width:100%;padding:8px;margin-bottom:6px;background:#22543d;color:#9ae6b4;border:none;border-radius:6px;cursor:pointer;text-align:left;";
    tool1.onclick = function () { window.open(AVATAR_SERVER + "/web/preprocess.html", "_blank"); };
    panel.appendChild(tool1);
    var tool2 = document.createElement("button");
    tool2.textContent = "🗂 数字人主页（素材配置/试听）";
    tool2.style.cssText = "width:100%;padding:8px;margin-bottom:10px;background:#1c2f4f;color:#9fc3ff;border:none;border-radius:6px;cursor:pointer;text-align:left;";
    tool2.onclick = function () { window.open(AVATAR_SERVER + "/web/index.html", "_blank"); };
    panel.appendChild(tool2);
    var label = document.createElement("div");
    label.textContent = "当前人物";
    label.style.cssText = "margin:6px 0 4px;color:#9aa;";
    panel.appendChild(label);
    var sel = document.createElement("select");
    sel.style.cssText = "width:100%;padding:5px;background:#222a36;color:#eee;border:1px solid #3a4048;border-radius:6px;";
    var optTest = document.createElement("option");
    optTest.value = "test"; optTest.textContent = "测试数字人（内置）";
    sel.appendChild(optTest);
    fetch(AVATAR_SERVER + "/api/libs")
      .then(function (r) { return r.json(); })
      .then(function (d) {
        // 并行读取每个素材库的 manifest，显示角色名（meta.person）；隐藏 lib_test* 测试库
        var libs = (d.libs || []).filter(function (n) { return n.indexOf("lib_test") !== 0; });
        var jobs = libs.map(function (lib) {
          return fetch(AVATAR_SERVER + "/api/lib/" + lib + "/manifest.json")
            .then(function (r) { return r.json(); })
            .then(function (m) {
              var person = (m && m.meta && m.meta.person) ? String(m.meta.person).trim() : "";
              var label = person ? person + "（" + lib + "）" : lib;
              return { lib: lib, label: label };
            })
            .catch(function () { return { lib: lib, label: lib }; });
        });
        return Promise.all(jobs);
      })
      .then(function (items) {
        items.forEach(function (it) {
          var o = document.createElement("option");
          o.value = it.lib; o.textContent = "素材: " + it.label;
          sel.appendChild(o);
        });
        sel.value = cfg.person;
      })
      .catch(function () {});
    sel.onchange = function () { cfg.person = sel.value; saveCfg(); refreshPerson(); logUI("切换数字人", "切换到 " + sel.value); };
    panel.appendChild(sel);
    // 删除当前选中素材库（2026-08-23 新增：下拉删除功能）
    var delBtn = document.createElement("button");
    delBtn.textContent = "🗑 删除当前人物（不可恢复）";
    delBtn.style.cssText = "width:100%;padding:7px;margin-top:6px;background:#3a2430;color:#ff9a9a;border:none;border-radius:6px;cursor:pointer;text-align:left;font-size:12px;";
    delBtn.onclick = function () {
      var lib = sel.value;
      if (!lib || lib === "test") { logUI("删除数字人", "尝试删除内置测试数字人，被拒"); alert("内置测试数字人不可删除"); return; }
      if (!confirm("确定删除人物「" + lib + "」吗？删除后不可恢复。")) { logUI("删除数字人", "用户取消删除 " + lib); return; }
      logUI("删除数字人", "开始删除 " + lib);
      fetch(AVATAR_SERVER + "/api/lib/" + lib, { method: "DELETE" })
        .then(function (r) { return r.json(); })
        .then(function (j) {
          if (j && j.ok) {
            logUI("删除数字人", "删除成功 " + lib + "，剩余: " + JSON.stringify(j));
            alert("已删除：" + lib);
            // 若删的是当前人物，切回测试数字人
            if (cfg.person === lib) { cfg.person = "test"; saveCfg(); refreshPerson(); }
            // 重建下拉选项（保留"测试数字人"）
            while (sel.options.length > 1) sel.remove(sel.options.length - 1);
            sel.value = "test";
            return fetch(AVATAR_SERVER + "/api/libs")
              .then(function (r) { return r.json(); })
              .then(function (d) {
                var libs = (d.libs || []).filter(function (n) { return n.indexOf("lib_test") !== 0; });
                var jobs = libs.map(function (l) {
                  return fetch(AVATAR_SERVER + "/api/lib/" + l + "/manifest.json")
                    .then(function (r) { return r.json(); })
                    .then(function (m) {
                      var person = (m && m.meta && m.meta.person) ? String(m.meta.person).trim() : "";
                      return { lib: l, label: person ? person + "（" + l + "）" : l };
                    })
                    .catch(function () { return { lib: l, label: l }; });
                });
                return Promise.all(jobs);
              })
              .then(function (items) {
                items.forEach(function (it) {
                  var o = document.createElement("option");
                  o.value = it.lib; o.textContent = "素材: " + it.label;
                  sel.appendChild(o);
                });
              });
          } else {
            logUI("删除数字人", "删除失败(服务端返回): " + JSON.stringify(j));
            alert("删除失败：" + ((j && j.error) || "未知错误"));
          }
        })
        .catch(function (e) {
          logUI("删除数字人", "删除失败(网络): " + (e && e.message ? e.message : String(e)));
          alert("删除失败：无法连接数字人服务");
        });
    };
    panel.appendChild(delBtn);
    var l2 = document.createElement("div");
    l2.textContent = "画面大小（也可直接拉窗口右下角手柄）";
    l2.style.cssText = "margin:8px 0 4px;color:#9aa;";
    panel.appendChild(l2);
    var sizeSel = document.createElement("select");
    sizeSel.style.cssText = "width:100%;padding:5px;background:#222a36;color:#eee;border:1px solid #3a4048;border-radius:6px;";
    [["s", "小"], ["m", "中"], ["l", "大"]].forEach(function (p) {
      var o = document.createElement("option"); o.value = p[0]; o.textContent = p[1];
      if (p[0] === cfg.size) o.selected = true;
      sizeSel.appendChild(o);
    });
    sizeSel.onchange = function () { cfg.size = sizeSel.value; cfg.customW = 0; saveCfg(); applySize(); };
    panel.appendChild(sizeSel);
    var hideBtn = document.createElement("button");
    hideBtn.textContent = "隐藏数字人（右上角 🎭 可恢复）";
    hideBtn.style.cssText = "margin-top:12px;width:100%;padding:7px;background:#3a2430;color:#ff9a9a;border:none;border-radius:6px;cursor:pointer;";
    hideBtn.onclick = function () { hideWindow(); document.body.removeChild(panel); };
    panel.appendChild(hideBtn);
    var done = document.createElement("button");
    done.textContent = "完成";
    done.style.cssText = "margin-top:8px;width:100%;padding:7px;background:#2b6cb0;color:#fff;border:none;border-radius:6px;cursor:pointer;";
    done.onclick = function () { document.body.removeChild(panel); };
    panel.appendChild(done);
    document.body.appendChild(panel);
  }

  // ---------- 初始化 ----------
  loadCfg();
  function init() {
    if (cfg.enabled) {
      buildWindow();
      refreshPerson();
    } else {
      showRestoreButton();
    }
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();




// ===== 系统定义生成工具（2026-09-01 恢复）=====
// 右下角 🧠 悬浮：选模型 → 粘贴资料 → 自动总结成系统定义 → 写入
// （params.system + meta.system 双写，新对话生效）。登录后可见（守卫在下方统一控制）。
(function () {
  var BTN_TOP = 52;
  var GENERATE_PROMPT = "你是提示词工程专家。下面提供一份资料，请把它提炼成一份简洁、可直接作为系统提示词（system prompt）使用的文本。要求：用中文、以第二人称\"你是……\"书写；按【角色定位】【核心职责】【必备知识】【语气风格】【注意事项】组织；语言精炼，全文不超过 600 字，不要客套话、不要解释性前言、不要 markdown 标题符号（可用分段）；只输出系统提示词正文。\n\n资料：\n";

  function btn() {
    var b = document.createElement("button");
    b.id = "dsh-defgen-btn";
    b.textContent = "🧠";
    b.title = "系统定义生成（选模型 + 填资料 → 自动总结成系统定义）";
    b.style.cssText = "position:fixed;bottom:64px;right:16px;z-index:2147483000;background:#1a2332;border:1px solid #3a4048;color:#8ab4f8;font-size:20px;width:42px;height:42px;border-radius:50%;cursor:pointer;box-shadow:0 4px 14px rgba(0,0,0,.35);display:flex;align-items:center;justify-content:center;";
    return b;
  }

  function openPanel(trigger) {
    var panel = document.createElement("div");
    panel.style.cssText = "position:fixed;bottom:116px;right:16px;z-index:2147483001;width:440px;max-width:92vw;max-height:82vh;overflow:auto;background:#171c24;border:1px solid #3a4048;border-radius:12px;padding:14px;color:#eee;font-size:13px;font-family:system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.6);";

    var title = document.createElement("div");
    title.textContent = "🧠 系统定义生成";
    title.style.cssText = "font-weight:600;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;";
    var close = document.createElement("button");
    close.textContent = "✕";
    close.style.cssText = "background:none;border:none;color:#888;font-size:14px;cursor:pointer;";
    close.onclick = function () { document.body.removeChild(panel); };
    title.appendChild(close);
    panel.appendChild(title);

    var l1 = document.createElement("div");
    l1.textContent = "目标模型";
    l1.style.cssText = "margin:6px 0 4px;color:#9aa;";
    panel.appendChild(l1);
    var sel = document.createElement("select");
    sel.style.cssText = "width:100%;padding:6px;background:#222a36;color:#eee;border:1px solid #3a4048;border-radius:6px;";
    var opt0 = document.createElement("option");
    opt0.value = "";
    opt0.textContent = "加载中…";
    sel.appendChild(opt0);
    panel.appendChild(sel);
    fetch("/api/v1/models", { method: "GET", headers: { "Authorization": "Bearer " + (localStorage.getItem("token") || "") } })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        sel.innerHTML = "";
        (d.data || []).forEach(function (m) {
          if (/bge|embed/i.test(m.id)) return;
          var o = document.createElement("option");
          o.value = m.id;
          o.textContent = (m.name && m.name !== m.id ? m.name + " (" + m.id + ")" : m.id);
          sel.appendChild(o);
        });
        if (!sel.options.length) {
          var o = document.createElement("option");
          o.value = "";
          o.textContent = "（没有可用模型）";
          sel.appendChild(o);
        }
      })
      .catch(function () {
        sel.innerHTML = "";
        var o = document.createElement("option");
        o.value = "";
        o.textContent = "（加载模型失败）";
        sel.appendChild(o);
      });

    var curBox = document.createElement("div");
    curBox.style.cssText = "margin-top:8px;background:#0f141c;border:1px solid #2a313c;border-radius:6px;padding:8px;color:#8a94a6;font-size:12px;max-height:90px;overflow:auto;white-space:pre-wrap;";
    curBox.textContent = "选择模型后显示当前系统定义…";
    panel.appendChild(curBox);
    sel.onchange = function () {
      var mid = sel.value;
      if (!mid) return;
      curBox.textContent = "读取中…";
      fetch("/api/v1/models/model?id=" + encodeURIComponent(mid), { method: "GET", headers: { "Authorization": "Bearer " + (localStorage.getItem("token") || "") } })
        .then(function (r) { return r.json(); })
        .then(function (m) {
          var sys = (m && m.params && m.params.system) || (m && m.meta && m.meta.system) || "";
          curBox.textContent = sys ? "当前系统定义（前 400 字）：\n" + sys.slice(0, 400) : "（该模型当前没有系统定义）";
        })
        .catch(function () { curBox.textContent = "（读取失败）"; });
    };

    var l2 = document.createElement("div");
    l2.textContent = "资料（粘贴角色设定 / 背景 / 知识 / 要求等）";
    l2.style.cssText = "margin:10px 0 4px;color:#9aa;";
    panel.appendChild(l2);
    var ta = document.createElement("textarea");
    ta.placeholder = "在这里粘贴资料…";
    ta.style.cssText = "width:100%;height:120px;padding:8px;background:#0f141c;color:#eee;border:1px solid #2a313c;border-radius:6px;resize:vertical;font-family:inherit;";
    panel.appendChild(ta);

    var gen = document.createElement("button");
    gen.textContent = "✨ 生成系统定义";
    gen.style.cssText = "margin-top:8px;width:100%;padding:8px;background:#2b6cb0;color:#fff;border:none;border-radius:6px;cursor:pointer;";
    gen.onclick = function () {
      var mid = sel.value, text = (ta.value || "").trim();
      if (!mid) { status.textContent = "请先选择模型"; return; }
      if (!text) { status.textContent = "请先粘贴资料"; return; }
      gen.disabled = true;
      status.textContent = "生成中（本地模型总结，约 10~30 秒）…";
      fetch("/api/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + (localStorage.getItem("token") || "") },
        body: JSON.stringify({
          model: mid,
          messages: [{ role: "system", content: "You are a prompt engineering expert. Reply in Chinese." }, { role: "user", content: GENERATE_PROMPT + text.slice(0, 8000) }],
          stream: false,
          temperature: 0.3
        })
      }).then(function (r) { return r.json(); })
        .then(function (d) {
          gen.disabled = false;
          var content = (d.choices && d.choices[0] && d.choices[0].message && d.choices[0].message.content) || "";
          if (!content) { status.textContent = "生成失败：" + (d.error && d.error.message || "无输出"); return; }
          out.value = content.trim();
          status.textContent = "已生成，可编辑后点击「写入该模型」";
        })
        .catch(function (e) { gen.disabled = false; status.textContent = "生成出错：" + e.message; });
    };
    panel.appendChild(gen);

    var l3 = document.createElement("div");
    l3.textContent = "生成的系统定义（可编辑）";
    l3.style.cssText = "margin:10px 0 4px;color:#9aa;";
    panel.appendChild(l3);
    var out = document.createElement("textarea");
    out.style.cssText = "width:100%;height:150px;padding:8px;background:#0f141c;color:#d6dbe4;border:1px solid #2a313c;border-radius:6px;resize:vertical;font-family:inherit;";
    panel.appendChild(out);

    var save = document.createElement("button");
    save.textContent = "💾 写入该模型的系统定义";
    save.style.cssText = "margin-top:8px;width:100%;padding:8px;background:#22543d;color:#9ae6b4;border:none;border-radius:6px;cursor:pointer;";
    save.onclick = function () {
      var mid = sel.value, newSys = (out.value || "").trim();
      if (!mid) { status.textContent = "请先选择模型"; return; }
      if (!newSys) { status.textContent = "生成结果为空，无法写入"; return; }
      save.disabled = true;
      status.textContent = "写入中…";
      fetch("/api/v1/models/model?id=" + encodeURIComponent(mid), { method: "GET", headers: { "Authorization": "Bearer " + (localStorage.getItem("token") || "") } })
        .then(function (r) { return r.json(); })
        .then(function (m) {
          if (!m || !m.id) throw new Error("模型不存在或无权访问");
          var meta = m.meta || {};
          meta.system = newSys;
          var params = m.params || {};
          params.system = newSys;
          return fetch("/api/v1/models/model/update", {
            method: "POST",
            headers: { "Content-Type": "application/json", "Authorization": "Bearer " + (localStorage.getItem("token") || "") },
            body: JSON.stringify({ id: m.id, name: m.name, meta: meta, params: params, access_grants: [] })
          }).then(function (r) { return r.json(); });
        })
        .then(function (res) {
          save.disabled = false;
          try { if (window.__dshLogUI) window.__dshLogUI("写系统定义", mid + " 写入 " + newSys.length + " 字 -> " + (res && res.id ? "成功" : JSON.stringify(res).slice(0,120))); } catch (e) {}
          if (res && res.id) {
            status.textContent = "✅ 已写入 " + res.id + " 的系统定义（" + newSys.length + " 字）。新对话生效。";
            curBox.textContent = "当前系统定义（前 400 字）：\n" + newSys.slice(0, 400);
          } else {
            status.textContent = "写入返回异常：" + JSON.stringify(res).slice(0, 120);
          }
        })
        .catch(function (e) { save.disabled = false; status.textContent = "写入出错：" + e.message; });
    };
    panel.appendChild(save);

    var status = document.createElement("div");
    status.textContent = "";
    status.style.cssText = "margin-top:8px;color:#8ab4f8;font-size:12px;min-height:16px;";
    panel.appendChild(status);

    document.body.appendChild(panel);
  }

  function initDefGen() {
    if (document.getElementById("dsh-defgen-btn")) return;
    var b = btn();
    b.onclick = function () { openPanel(b); };
    document.body.appendChild(b);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initDefGen);
  } else {
    initDefGen();
  }
})();




// ===== 悬浮登录守卫（2026-09-01）=====
// 数字人窗口 / 🎭 恢复按钮 / 🧠 系统定义按钮：仅登录后显示，未登录隐藏。
// 登录后恢复原显示状态（不干扰数字人自身的显示/隐藏逻辑）。
(function () {
  var IDS = ["dsh-avatar-win", "dsh-avatar-restore", "dsh-defgen-btn"];
  function apply() {
    var logged = !!localStorage.getItem("token");
    IDS.forEach(function (id) {
      var el = document.getElementById(id);
      if (!el) return;
      if (!logged) {
        if (el.dataset.dshPrev === undefined) el.dataset.dshPrev = el.style.display || "";
        el.style.display = "none";
      } else if (el.dataset.dshPrev !== undefined) {
        el.style.display = el.dataset.dshPrev;
        delete el.dataset.dshPrev;
      }
    });
  }
  apply();
  setInterval(apply, 1000);
})();



// ===== 用户访问页面 v2（微信风格 · 科技感，2026-09-01）=====
// 登录区分：admin → 管理界面；普通用户 → 本页面。
// 微信布局：底部 tab（微信/通讯录/发现/我）+ 会话列表 + 聊天（打字 + 语音输入 + AI 语音回复）。
// 语音输入：按住 🎤 录音 → SenseVoice 转文字 → 发送；AI 回复可 🔊 语音播放（按模型音色）。
(function () {
  if (window.__dshUserPageLoaded) return;
  window.__dshUserPageLoaded = true;

  function token() { return localStorage.getItem("token") || ""; }
  function api(url, opts) {
    opts = opts || {};
    opts.headers = opts.headers || {};
    opts.headers["Authorization"] = "Bearer " + token();
    if (opts.json !== undefined) {
      opts.headers["Content-Type"] = "application/json";
      opts.body = JSON.stringify(opts.json);
      delete opts.json;
    }
    return fetch(url, opts);
  }
  function esc(s) { var d = document.createElement("div"); d.textContent = s == null ? "" : String(s); return d.innerHTML; }

  var histories = {};      // 会话历史（按联系人 id，内存缓存）
  var chatIds = {};        // 联系人 id -> Open WebUI 会话 id（服务端持久化）
  var currentContact = null;
  var currentTab = "wechat";
  var contacts = [];       // 联系人列表
  var voiceCache = {};     // 联系人 voice 缓存
  var aiSpeaking = false;
  var callView = null, callRec = null, callChunks = [], callBusy = false;
  var rec = null;          // MediaRecorder

  // ============ UI 骨架 ============
  function build() {
    var root = document.createElement("div");
    root.id = "dsh-user-page";
    root.style.cssText = "position:fixed;inset:0;z-index:2147483500;display:flex;background:linear-gradient(160deg,#0a0f24 0%,#141a3a 55%,#0c1a2e 100%);font-family:system-ui,'Microsoft YaHei',sans-serif;color:#e8ecf8;overflow:hidden;";
    root.innerHTML =
      '<div id="dsh-up-left" style="width:330px;min-width:280px;flex-shrink:0;display:flex;flex-direction:column;background:rgba(255,255,255,.04);border-right:1px solid rgba(255,255,255,.08);backdrop-filter:blur(14px);">' +
        '<div id="dsh-up-head" style="display:flex;align-items:center;justify-content:space-between;padding:16px 18px 12px;border-bottom:1px solid rgba(255,255,255,.08);">' +
          '<div style="font-size:18px;font-weight:700;letter-spacing:1px;background:linear-gradient(90deg,#00e5ff,#a78bfa);-webkit-background-clip:text;background-clip:text;color:transparent;" id="dsh-up-title">知音</div>' +
          '<div id="dsh-up-me-avatar" style="width:34px;height:34px;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c4dff);display:flex;align-items:center;justify-content:center;font-size:15px;cursor:pointer;">✦</div>' +
        '</div>' +
        '<div id="dsh-up-list" style="flex:1;overflow-y:auto;padding:8px;"></div>' +
        '<div id="dsh-up-tabbar" style="display:flex;border-top:1px solid rgba(255,255,255,.08);background:rgba(10,15,36,.6);">' +
          tabItem("wechat", "💬", "微信") + tabItem("contacts", "👥", "通讯录") + tabItem("discover", "🧭", "发现") + tabItem("me", "👤", "我") +
        '</div>' +
      '</div>' +
      '<div id="dsh-up-chat" style="flex:1;display:flex;flex-direction:column;min-width:0;">' +
        '<div id="dsh-up-chat-head" style="display:none;padding:12px 16px;background:rgba(255,255,255,.04);border-bottom:1px solid rgba(255,255,255,.08);align-items:center;gap:12px;">' +
          '<button id="dsh-up-back" style="display:none;background:none;border:none;color:#00e5ff;font-size:22px;cursor:pointer;padding:0 6px;">‹</button>' +
          '<div id="dsh-up-chat-avatar" style="width:36px;height:36px;border-radius:50%;background:linear-gradient(135deg,#f59e0b,#ef4444);display:flex;align-items:center;justify-content:center;font-size:15px;color:#fff;">✦</div>' +
          '<div style="flex:1;"><div id="dsh-up-chat-name" style="font-size:15px;font-weight:600;">联系人</div>' +
          '<div style="font-size:11px;color:#8b93b8;">在线</div></div>' +
          '<button id="dsh-up-voice-all" title="朗读最后一条回复" style="background:linear-gradient(135deg,#00e5ff,#7c4dff);border:none;color:#fff;width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:15px;">🔊</button>' +
        '</div>' +
        '<div id="dsh-up-msg" style="flex:1;overflow-y:auto;padding:16px 14px;display:flex;flex-direction:column;gap:12px;"></div>' +
        '<div id="dsh-up-inputbar" style="display:none;padding:10px 12px 14px;border-top:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.03);">' +
          '<div style="display:flex;gap:10px;align-items:center;">' +
            '<button id="dsh-up-call" title="语音通话：像打电话一样对话，你说一句它语音回答" style="width:42px;height:42px;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c4dff);border:none;color:#fff;font-size:18px;cursor:pointer;flex-shrink:0;">📞</button>' +
            '<button id="dsh-up-rec" title="按住说话，松开发送语音" style="width:42px;height:42px;border-radius:50%;background:linear-gradient(135deg,#ef4444,#f97316);border:none;color:#fff;font-size:18px;cursor:pointer;flex-shrink:0;user-select:none;-webkit-user-select:none;">🎤</button>' +
            '<input id="dsh-up-input" type="text" placeholder="输入消息…" style="flex:1;padding:11px 14px;border-radius:22px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.07);color:#e8ecf8;outline:none;font-size:14px;"/>' +
            '<button id="dsh-up-send" style="background:linear-gradient(135deg,#00e5ff,#7c4dff);border:none;color:#fff;padding:10px 20px;border-radius:22px;cursor:pointer;font-size:14px;font-weight:600;">发送</button>' +
          '</div>' +
          '<div id="dsh-up-rec-tip" style="display:none;text-align:center;color:#f97316;font-size:12px;margin-top:6px;">🎙 正在录音…松开发送</div>' +
        '</div>' +
      '</div>';
    document.body.appendChild(root);

    document.getElementById("dsh-up-back").onclick = backToChats;
    document.getElementById("dsh-up-send").onclick = sendMessage;
    document.getElementById("dsh-up-voice-all").onclick = speakLastAi;
    document.getElementById("dsh-up-me-avatar").onclick = function () { switchTab("me"); };
    var inp = document.getElementById("dsh-up-input");
    inp.addEventListener("keydown", function (e) { if (e.key === "Enter") sendMessage(); });
    bindRecorder(document.getElementById("dsh-up-rec"));
    document.getElementById("dsh-up-call").onclick = openCallView;
    loadContacts();
    onResize();
    window.addEventListener("resize", onResize);
  }

  function tabItem(id, icon, label) {
    return '<div data-tab="' + id + '" onclick="(window.__dshUserPage && window.__dshUserPage.switchTab(\'' + id + '\'))" style="flex:1;text-align:center;padding:8px 0 10px;cursor:pointer;color:#8b93b8;font-size:11px;">' +
      '<div style="font-size:18px;margin-bottom:2px;">' + icon + '</div>' + label + '</div>';
  }
  window.__dshUserPage = { switchTab: switchTab };

  function switchTab(id) {
    currentTab = id;
    currentContact = null;
    onResize();
    if (id === "wechat") renderChatList();
    else if (id === "contacts") renderContacts();
    else if (id === "discover") renderDiscover();
    else if (id === "me") renderMe();
    var title = { wechat: "知音", contacts: "通讯录", discover: "发现", me: "我" }[id];
    document.getElementById("dsh-up-title").textContent = title;
    document.querySelectorAll("#dsh-up-tabbar [data-tab]").forEach(function (el) {
      el.style.color = el.dataset.tab === id ? "#00e5ff" : "#8b93b8";
    });
  }

  function onResize() {
    var narrow = window.innerWidth < 768;
    var left = document.getElementById("dsh-up-left");
    if (!left) return;
    if (narrow) {
      // 手机端：单页占满，左侧栏 100% 宽，不留边
      left.style.width = "100%";
      left.style.minWidth = "0";
      left.style.borderRight = "none";
      left.style.display = currentContact ? "none" : "flex";
      document.getElementById("dsh-up-chat").style.display = currentContact ? "flex" : "none";
      document.getElementById("dsh-up-back").style.display = "block";
    } else {
      left.style.width = "330px";
      left.style.minWidth = "280px";
      left.style.borderRight = "1px solid rgba(255,255,255,.08)";
      left.style.display = "flex";
      document.getElementById("dsh-up-chat").style.display = "flex";
      document.getElementById("dsh-up-back").style.display = "none";
    }
    var head = document.getElementById("dsh-up-chat-head");
    var bar = document.getElementById("dsh-up-inputbar");
    head.style.display = currentContact ? "flex" : "none";
    bar.style.display = currentContact ? "block" : "none";
  }

  function backToChats() { currentContact = null; onResize(); }

  // ============ 通讯录 / 会话 ============
  function loadContacts() {
    api("/api/v1/models").then(function (r) { return r.json(); }).then(function (d) {
      contacts = (d.data || []).filter(function (m) { return !/bge|embed/i.test(m.id); });
      // 从列表接口直接读每个模型的声音（详情接口对普通用户 401，不能依赖它）
      contacts.forEach(function (m) {
        var tts = m.info && m.info.meta && m.info.meta.tts;
        if (tts && tts.voice) voiceCache[m.id] = tts.voice;
      });
      renderContacts();
    }).catch(function () {});
  }

  var COLORS = ["linear-gradient(135deg,#00e5ff,#7c4dff)", "linear-gradient(135deg,#f59e0b,#ef4444)", "linear-gradient(135deg,#22c55e,#0ea5e9)", "linear-gradient(135deg,#e879f9,#6366f1)", "linear-gradient(135deg,#f97316,#dc2626)"];

  function contactName(m) { return m.name && m.name !== m.id ? m.name : m.id; }

  function renderContacts() {
    var list = document.getElementById("dsh-up-list");
    if (currentTab !== "contacts" && currentTab !== "wechat") return;
    if (currentTab === "wechat") { renderChatList(); return; }
    list.innerHTML = "";
    contacts.forEach(function (m, i) {
      var name = contactName(m);
      var item = document.createElement("div");
      item.style.cssText = "display:flex;align-items:center;gap:12px;padding:11px 12px;border-radius:12px;cursor:pointer;";
      item.onmouseenter = function () { item.style.background = "rgba(255,255,255,.07)"; };
      item.onmouseleave = function () { item.style.background = "transparent"; };
      item.innerHTML =
        '<div style="width:42px;height:42px;border-radius:50%;background:' + COLORS[i % 5] + ';display:flex;align-items:center;justify-content:center;color:#fff;font-size:17px;flex-shrink:0;">' + esc(name.charAt(0)) + '</div>' +
        '<div style="flex:1;min-width:0;"><div style="font-size:14px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + esc(name) + '</div>' +
        '<div style="font-size:11px;color:#8b93b8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + esc(m.id) + '</div></div>';
      item.onclick = function () { openChat(m); };
      list.appendChild(item);
    });
    if (!contacts.length) list.innerHTML = '<div style="color:#8b93b8;font-size:13px;padding:16px;text-align:center;">暂无联系人</div>';
  }

  function renderChatList() {
    var list = document.getElementById("dsh-up-list");
    list.innerHTML = "";
    var keys = Object.keys(histories).filter(function (k) { return histories[k].length > 0; });
    if (!keys.length) { list.innerHTML = '<div style="color:#8b93b8;font-size:13px;padding:20px;text-align:center;">还没有会话<br/>去「通讯录」选个人聊聊吧</div>'; return; }
    keys.forEach(function (id) {
      var msgs = histories[id];
      var last = msgs[msgs.length - 1];
      var contact = contacts.find(function (c) { return c.id === id; });
      var name = contact ? contactName(contact) : id;
      var item = document.createElement("div");
      item.style.cssText = "display:flex;align-items:center;gap:12px;padding:11px 12px;border-radius:12px;cursor:pointer;";
      item.onmouseenter = function () { item.style.background = "rgba(255,255,255,.07)"; };
      item.onmouseleave = function () { item.style.background = "transparent"; };
      item.innerHTML =
        '<div style="width:42px;height:42px;border-radius:50%;background:' + COLORS[(keys.indexOf(id)) % 5] + ';display:flex;align-items:center;justify-content:center;color:#fff;font-size:17px;flex-shrink:0;">' + esc(name.charAt(0)) + '</div>' +
        '<div style="flex:1;min-width:0;"><div style="font-size:14px;font-weight:600;">' + esc(name) + '</div>' +
        '<div style="font-size:11px;color:#8b93b8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + esc(last.content) + '</div></div>';
      item.onclick = function () { openChat(contact || { id: id, name: id }); };
      list.appendChild(item);
    });
  }

  function renderDiscover() {
    document.getElementById("dsh-up-list").innerHTML =
      '<div style="color:#8b93b8;font-size:13px;padding:20px;text-align:center;line-height:2;">🧭 发现<br/>更多功能建设中…</div>';
  }

  function renderMe() {
    var list = document.getElementById("dsh-up-list");
    api("/api/v1/auths/").then(function (r) { return r.json(); }).then(function (u) {
      list.innerHTML =
        '<div style="text-align:center;padding:30px 0 20px;">' +
          '<div style="width:64px;height:64px;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c4dff);display:flex;align-items:center;justify-content:center;font-size:26px;margin:0 auto 12px;">' + esc((u.name || "U").charAt(0)) + '</div>' +
          '<div style="font-size:16px;font-weight:600;">' + esc(u.name || "-") + '</div>' +
          '<div style="font-size:12px;color:#8b93b8;margin-top:4px;">' + esc(u.email || "") + '</div>' +
        '</div>' +
        '<div style="padding:0 14px;"><button id="dsh-up-logout" style="width:100%;padding:11px;border-radius:10px;border:1px solid rgba(239,68,68,.5);background:rgba(239,68,68,.12);color:#f87171;cursor:pointer;font-size:14px;">退出登录</button></div>';
      document.getElementById("dsh-up-logout").onclick = function () {
        localStorage.removeItem("token");
        location.reload();
      };
    }).catch(function () {});
  }

  // ============ 会话服务端持久化（Open WebUI chat） ============
  function findChatId(contactId) {
    return api("/api/v1/chats/list").then(function (r) { return r.json(); }).then(function (list) {
      if (Array.isArray(list)) {
        for (var i = 0; i < list.length; i++) {
          if (list[i].title === contactId) return list[i].id;
        }
      }
      return null;
    }).catch(function () { return null; });
  }

  function loadChatHistory(contactId, cb) {
    findChatId(contactId).then(function (chatId) {
      if (!chatId) { cb && cb(); return; }
      chatIds[contactId] = chatId;
      api("/api/v1/chats/" + chatId).then(function (r) { return r.json(); }).then(function (data) {
        var inner = (data && data.chat) || {};
        var hist = inner.history || {};
        var msgs = hist.messages || {};
        var list = Array.isArray(msgs) ? msgs : Object.keys(msgs).map(function (k) { return msgs[k]; });
        histories[contactId] = list.map(function (m) {
          return { role: m.role === "assistant" ? "ai" : "user", content: m.content || "" };
        });
        cb && cb();
      }).catch(function () { cb && cb(); });
    }).catch(function () { cb && cb(); });
  }

  function saveChat(contactId) {
    var msgs = histories[contactId] || [];
    var messages = {};
    msgs.forEach(function (m, i) {
      var mid = "m" + (i + 1) + "-" + (Date.now() % 100000);
      messages[mid] = { id: mid, role: m.role === "ai" ? "assistant" : "user", content: m.content };
    });
    var ids = Object.keys(messages);
    var history = { currentId: ids.length ? ids[ids.length - 1] : null, messages: messages };
    if (chatIds[contactId]) {
      return api("/api/v1/chats/" + chatIds[contactId], { method: "POST", json: { chat: { history: history } } }).catch(function () {});
    }
    return api("/api/v1/chats/new", {
      method: "POST",
      json: { chat: { id: "chat-" + Date.now() + "-" + Math.random().toString(16).slice(2, 8), title: contactId, history: history } }
    }).then(function (r) { return r.json(); }).then(function (chat) {
      if (chat && chat.id) chatIds[contactId] = chat.id;
    }).catch(function () {});
  }

  // ============ 聊天 ============
  function openChat(m) {
    currentContact = m;
    currentContact.voice = voiceCache[m.id] || "azhong";  // 声音在通讯录加载时已缓存
    var name = contactName(m);
    document.getElementById("dsh-up-chat-name").textContent = name;
    document.getElementById("dsh-up-chat-avatar").textContent = name.charAt(0);
    var box = document.getElementById("dsh-up-msg");
    box.innerHTML = "";
    var msgs = histories[m.id] || [];
    msgs.forEach(function (msg) { renderMsg(msg.role, msg.content); });
    if (!msgs.length) renderMsg("ai", "你好，我是 " + name + "。有什么想聊的？");
    onResize();
    // 从服务端加载历史会话（刷新后恢复聊天记录）
    loadChatHistory(m.id, function () {
      if (!currentContact || currentContact.id !== m.id) return;
      var h = histories[m.id] || [];
      box.innerHTML = "";
      h.forEach(function (msg) { renderMsg(msg.role, msg.content); });
      if (!h.length) renderMsg("ai", "你好，我是 " + name + "。有什么想聊的？");
    });
  }

  function renderMsg(role, content) {
    var box = document.getElementById("dsh-up-msg");
    var row = document.createElement("div");
    row.style.cssText = "display:flex;align-items:flex-start;gap:8px;" + (role === "user" ? "flex-direction:row-reverse;" : "");
    row.innerHTML =
      '<div style="width:32px;height:32px;border-radius:50%;flex-shrink:0;background:' + (role === "user" ? "linear-gradient(135deg,#22c55e,#0ea5e9)" : "linear-gradient(135deg,#f59e0b,#ef4444)") + ';display:flex;align-items:center;justify-content:center;color:#fff;font-size:13px;">' + (role === "user" ? "我" : "✦") + '</div>' +
      '<div style="max-width:72%;padding:10px 14px;border-radius:14px;font-size:14px;line-height:1.6;word-break:break-word;white-space:pre-wrap;background:' + (role === "user" ? "linear-gradient(135deg,#00e5ff,#7c4dff)" : "rgba(255,255,255,.08)") + ';color:' + (role === "user" ? "#fff" : "#e8ecf8") + ';' + (role === "user" ? "border-top-right-radius:4px;" : "border-top-left-radius:4px;") + '">' + esc(content) + '</div>';
    if (role === "ai") {
      var vb = document.createElement("button");
      vb.textContent = "🔊";
      vb.title = "播放语音";
      vb.style.cssText = "background:none;border:none;cursor:pointer;font-size:15px;color:#00e5ff;padding:4px;flex-shrink:0;";
      vb.onclick = function () { speakText(content); };
      row.appendChild(vb);
    }
    box.appendChild(row);
    box.scrollTop = box.scrollHeight;
  }

  function sendMessage() {
    if (!currentContact) return;
    var inp = document.getElementById("dsh-up-input");
    var text = (inp.value || "").trim();
    if (!text) return;
    inp.value = "";
    var msgs = histories[currentContact.id] || (histories[currentContact.id] = []);
    msgs.push({ role: "user", content: text });
    renderMsg("user", text);
    var typing = renderTyping();
    api("/api/chat/completions", {
      method: "POST",
      json: { model: currentContact.id, messages: msgs.map(function (m) { return { role: m.role, content: m.content }; }), stream: false }
    }).then(function (r) { return r.json(); }).then(function (d) {
      var content = (d.choices && d.choices[0] && d.choices[0].message && d.choices[0].message.content) || "";
      if (!content) content = "（无回复：" + ((d.error && d.error.message) || "未知错误") + "）";
      typing.remove();
      msgs.push({ role: "ai", content: content });
      renderMsg("ai", content);
      saveChat(currentContact.id);  // 服务端持久化
    }).catch(function (e) {
      typing.remove();
      var msg = "请求失败：" + e.message;
      msgs.push({ role: "ai", content: msg });
      renderMsg("ai", msg);
    });
  }

  function renderTyping() {
    var box = document.getElementById("dsh-up-msg");
    var row = document.createElement("div");
    row.style.cssText = "display:flex;align-items:center;gap:8px;color:#8b93b8;font-size:13px;";
    row.innerHTML = '<div style="width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#f59e0b,#ef4444);display:flex;align-items:center;justify-content:center;font-size:13px;color:#fff;">✦</div><div>正在输入…</div>';
    box.appendChild(row);
    box.scrollTop = box.scrollHeight;
    return row;
  }

  // ============ 语音输入（按住说话） ============
  function bindRecorder(btn) {
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) return;
    var chunks = [];
    function start() {
      if (!currentContact || rec) return;
      document.getElementById("dsh-up-rec-tip").style.display = "block";
      navigator.mediaDevices.getUserMedia({ audio: true }).then(function (stream) {
        rec = new MediaRecorder(stream);
        chunks = [];
        rec.ondataavailable = function (e) { if (e.data.size) chunks.push(e.data); };
        rec.onstop = function () {
          stream.getTracks().forEach(function (t) { t.stop(); });
          var blob = new Blob(chunks, { type: rec.mimeType || "audio/webm" });
          rec = null;
          uploadVoice(blob);
        };
        rec.start();
      }).catch(function (e) {
        document.getElementById("dsh-up-rec-tip").style.display = "none";
        alert("无法使用麦克风：" + e.message);
      });
    }
    function stop() {
      document.getElementById("dsh-up-rec-tip").style.display = "none";
      if (rec && rec.state !== "inactive") rec.stop();
    }
    btn.addEventListener("mousedown", start);
    btn.addEventListener("mouseup", stop);
    btn.addEventListener("mouseleave", stop);
    btn.addEventListener("touchstart", function (e) { e.preventDefault(); start(); });
    btn.addEventListener("touchend", function (e) { e.preventDefault(); stop(); });
  }

  function uploadVoice(blob) {
    var fd = new FormData();
    fd.append("file", blob, "voice.webm");
    var tip = document.getElementById("dsh-up-rec-tip");
    tip.style.display = "block";
    tip.textContent = "🎙 正在识别语音…";
    api("/api/v1/audio/transcriptions", { method: "POST", body: fd }).then(function (r) { return r.json(); })
      .then(function (d) {
        tip.style.display = "none";
        var text = (d && d.text || "").trim();
        if (!text) { alert("没听清，再说一次？"); return; }
        document.getElementById("dsh-up-input").value = text;
        sendMessage();
      })
      .catch(function (e) { tip.style.display = "none"; alert("语音识别失败：" + e.message); });
  }

  // ============ AI 语音回复 ============
  function speakLastAi() {
    if (!currentContact) return;
    var msgs = histories[currentContact.id] || [];
    for (var i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "ai") { speakText(msgs[i].content); return; }
    }
  }
  function speakText(text) {
    if (!text || aiSpeaking) return;
    aiSpeaking = true;
    var v = (currentContact && currentContact.voice) || "azhong";
    api("/api/v1/audio/speech", {
      method: "POST",
      json: { model: v, input: text.slice(0, 600), voice: v }
    }).then(function (r) {
      if (!r.ok) throw new Error("语音服务返回 " + r.status);
      return r.blob();
    }).then(function (blob) {
      var url = URL.createObjectURL(blob);
      var a = new Audio(url);
      a.onended = function () { URL.revokeObjectURL(url); aiSpeaking = false; };
      a.onerror = function () { aiSpeaking = false; };
      a.play().catch(function () { aiSpeaking = false; });
    }).catch(function (e) { aiSpeaking = false; });
  }

  // ============ 语音通话界面（像打电话：自动聆听，无需按住） ============
  var callCtx = null, callAnalyser = null, callMediaStream = null;
  var callSilentMs = 0, callTalking = false, callVoiceStart = 0;

  function openCallView() {
    if (!currentContact || callView) return;
    var name = contactName(currentContact);
    var v = document.createElement("div");
    v.id = "dsh-up-callview";
    v.style.cssText = "position:fixed;inset:0;z-index:2147483700;background:radial-gradient(ellipse at center,#141a3a 0%,#0a0f24 70%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;color:#e8ecf8;font-family:system-ui,'Microsoft YaHei',sans-serif;";
    v.innerHTML =
      '<div style="width:100px;height:100px;border-radius:50%;background:linear-gradient(135deg,#00e5ff,#7c4dff);display:flex;align-items:center;justify-content:center;font-size:42px;color:#fff;box-shadow:0 0 44px rgba(0,229,255,.35);">' + esc(name.charAt(0)) + '</div>' +
      '<div style="font-size:20px;font-weight:700;">' + esc(name) + '</div>' +
      '<div id="dsh-call-status" style="font-size:15px;color:#8b93b8;min-height:24px;text-align:center;padding:0 30px;">接通中…</div>' +
      '<div style="font-size:12px;color:#5b6480;margin-top:10px;">' + esc(name) + ' 的语音通话 · 直接说话即可</div>' +
      '<button id="dsh-call-hangup" title="挂断" style="width:66px;height:66px;border-radius:50%;background:linear-gradient(135deg,#ef4444,#dc2626);border:none;color:#fff;font-size:22px;cursor:pointer;box-shadow:0 6px 20px rgba(239,68,68,.35);">📵</button>';
    document.body.appendChild(v);
    callView = v;
    document.getElementById("dsh-call-hangup").onclick = closeCallView;
    startAutoListen();
  }

  function closeCallView() {
    if (callRec) { try { callRec.stop(); } catch (e) {} callRec = null; }
    if (callCtx) { try { callCtx.close(); } catch (e) {} callCtx = null; callAnalyser = null; }
    if (callMediaStream) { callMediaStream.getTracks().forEach(function (t) { t.stop(); }); callMediaStream = null; }
    callTalking = false; callSilentMs = 0; callBusy = false;
    if (callView) { document.body.removeChild(callView); callView = null; }
  }

  function setCallStatus(t) { var s = document.getElementById("dsh-call-status"); if (s) s.textContent = t; }

  // 自动聆听：录音 + 音量检测，检测到说完（静音 1.2s）自动停止处理
  function startAutoListen() {
    if (!currentContact || callBusy || callRec) return;
    setCallStatus("🎧 聆听中…请直接说话");
    navigator.mediaDevices.getUserMedia({ audio: true }).then(function (stream) {
      callMediaStream = stream;
      callRec = new MediaRecorder(stream);
      callChunks = [];
      callRec.ondataavailable = function (e) { if (e.data.size) callChunks.push(e.data); };
      callRec.onstop = function () {
        stream.getTracks().forEach(function (t) { t.stop(); });
        var blob = new Blob(callChunks, { type: callRec.mimeType || "audio/webm" });
        callRec = null;
        if (callCtx) { try { callCtx.close(); } catch (e) {} callCtx = null; callAnalyser = null; }
        processCallVoice(blob);
      };
      callRec.start();
      try { callCtx = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) {}
      if (callCtx) {
        var src = callCtx.createMediaStreamSource(stream);
        callAnalyser = callCtx.createAnalyser();
        callAnalyser.fftSize = 1024;
        src.connect(callAnalyser);
      }
      callTalking = false; callSilentMs = 0;
      vadLoop();
    }).catch(function (e) { setCallStatus("麦克风不可用：" + e.message); });
  }

  function vadLoop() {
    if (!callRec || callRec.state === "inactive" || !callAnalyser) return;
    var data = new Uint8Array(callAnalyser.fftSize);
    callAnalyser.getByteTimeDomainData(data);
    var sum = 0;
    for (var i = 0; i < data.length; i++) { var dv = (data[i] - 128) / 128; sum += dv * dv; }
    var rms = Math.sqrt(sum / data.length);
    if (rms > 0.035) {
      callSilentMs = 0;
      if (!callTalking) { callTalking = true; callVoiceStart = Date.now(); }
    } else if (callTalking) {
      callSilentMs += 100;
      if (callSilentMs >= 1200) {
        callTalking = false;
        if (Date.now() - callVoiceStart > 600) {
          if (callRec) { try { callRec.stop(); } catch (e) {} }
          return;
        } else {
          callSilentMs = 0;
        }
      }
    }
    setTimeout(vadLoop, 100);
  }

  function processCallVoice(blob) {
    callBusy = true;
    setCallStatus("🔍 识别中…");
    var fd = new FormData();
    fd.append("file", blob, "voice.webm");
    api("/api/v1/audio/transcriptions", { method: "POST", body: fd }).then(function (r) { return r.json(); })
      .then(function (d) {
        var text = (d && d.text || "").trim();
        if (!text) { setCallStatus("没听清，请再说一次"); callBusy = false; setTimeout(startAutoListen, 800); return; }
        setCallStatus("🧠 思考中…（你刚说：" + text.slice(0, 30) + "）");
        var msgs = histories[currentContact.id] || (histories[currentContact.id] = []);
        msgs.push({ role: "user", content: text });
        return api("/api/chat/completions", {
          method: "POST",
          json: { model: currentContact.id, messages: msgs.map(function (m) { return { role: m.role, content: m.content }; }), stream: false }
        }).then(function (r) { return r.json(); }).then(function (d2) {
          var content = (d2.choices && d2.choices[0] && d2.choices[0].message && d2.choices[0].message.content) || "";
          if (!content) content = "（无回复）";
          msgs.push({ role: "ai", content: content });
          if (currentContact) renderMsg("ai", content);
          saveChat(currentContact.id);  // 服务端持久化
          speakCallReply(content);
        });
      })
      .catch(function (e) { setCallStatus("出错：" + e.message); callBusy = false; setTimeout(startAutoListen, 1000); });
  }

  function speakCallReply(text) {
    setCallStatus("🔊 回复中…");
    var v = (currentContact && currentContact.voice) || "azhong";
    api("/api/v1/audio/speech", {
      method: "POST",
      json: { model: v, input: text.slice(0, 600), voice: v }
    }).then(function (r) { if (!r.ok) throw new Error("语音失败"); return r.blob(); })
      .then(function (blob) {
        var url = URL.createObjectURL(blob);
        var a = new Audio(url);
        var resume = function () { URL.revokeObjectURL(url); callBusy = false; if (callView) { setTimeout(startAutoListen, 400); } };
        a.onended = resume;
        a.onerror = resume;
        a.play().catch(resume);
      })
      .catch(function (e) { setCallStatus("语音播放失败：" + e.message); callBusy = false; setTimeout(startAutoListen, 1000); });
  }

  // ============ 登录区分主流程 ============
  // 角色确定后立即停止轮询（admin 不会建本页面，原实现会对 admin 每 2 秒
  // 打一次 /api/v1/auths/ 永不停止；退出登录走 location.reload，重载后重新检测）
  var timer = setInterval(function () {
    if (!localStorage.getItem("token")) return;
    if (document.getElementById("dsh-user-page")) { clearInterval(timer); return; }
    api("/api/v1/auths/").then(function (r) { return r.json(); }).then(function (u) {
      if (!u || !u.role) return;  // 未取到角色（接口异常/正在登录）：继续等
      if (u.role !== "admin") build();
      clearInterval(timer);
    }).catch(function () {});
  }, 2000);
})();












// ===== 数字人管理入口（admin 专用）=====
// 点击打开数字人建库页：默认直连本机素材服务 127.0.0.1:48620。
// 如需外网同域名反向代理访问，部署时定义全局变量即可覆盖：
//   window.__DSH_AVATAR_REMOTE__ = "https://your-domain.example/avatar"
(function () {
  function avatarUrl() {
    var remote = (typeof window.__DSH_AVATAR_REMOTE__ !== "undefined" && window.__DSH_AVATAR_REMOTE__) || "";
    if (remote) return remote + "/web/preprocess.html";
    return "http://127.0.0.1:48620/web/preprocess.html";
  }
  function showBtn() {
    if (document.getElementById("dsh-avatar-admin-btn")) return;
    var b = document.createElement("button");
    b.id = "dsh-avatar-admin-btn";
    b.textContent = "🎭";
    b.title = "数字人管理（建库/素材）";
    b.style.cssText = "position:fixed;bottom:64px;right:66px;z-index:2147483000;background:#1a2332;border:1px solid #3a4048;color:#f0abfc;font-size:20px;width:42px;height:42px;border-radius:50%;cursor:pointer;box-shadow:0 4px 14px rgba(0,0,0,.35);display:flex;align-items:center;justify-content:center;";
    b.onclick = function () { window.open(avatarUrl(), "_blank"); };
    document.body.appendChild(b);
  }
  var timer = setInterval(function () {
    if (!localStorage.getItem("token")) return;
    fetch("/api/v1/auths/", { headers: { "Authorization": "Bearer " + localStorage.getItem("token") } })
      .then(function (r) { return r.json(); })
      .then(function (u) {
        // 角色确定后停止轮询：admin 显示按钮；非 admin 本按钮不显示，
        // 原实现会对非 admin 每 2 秒查询一次永不停止
        if (u && u.role === "admin") { showBtn(); }
        if (u && u.role) clearInterval(timer);
      }).catch(function () {});
  }, 2000);
})();

// ===== 微信引导页（2026-09-01）=====
// 微信内置浏览器打开时：全屏引导用户用系统浏览器打开（绕开微信拦截提示）。
(function () {
  if (!/MicroMessenger/i.test(navigator.userAgent)) return;
  if (document.getElementById("dsh-wx-guide")) return;
  var url = location.href;
  var g = document.createElement("div");
  g.id = "dsh-wx-guide";
  g.style.cssText = "position:fixed;inset:0;z-index:2147483800;background:#0a0f24;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;color:#e8ecf8;font-family:system-ui,'Microsoft YaHei',sans-serif;text-align:center;padding:28px;";
  g.innerHTML =
    '<div style="font-size:22px;font-weight:700;background:linear-gradient(90deg,#00e5ff,#a78bfa);-webkit-background-clip:text;background-clip:text;color:transparent;">知音 · 请用浏览器打开</div>' +
    '<div style="font-size:14px;color:#8b93b8;line-height:1.9;">微信内置浏览器可能无法正常访问<br/>请点击右上角 <b style="color:#fff;">「···」</b> 选择<br/><b style="color:#00e5ff;">「在浏览器中打开」</b></div>' +
    '<div style="font-size:13px;color:#5b6480;">或复制下方链接到浏览器粘贴访问</div>' +
    '<div style="max-width:92%;word-break:break-all;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);border-radius:10px;padding:10px 14px;font-size:12px;color:#cbd5e1;">' + url + '</div>' +
    '<button id="dsh-wx-copy" style="background:linear-gradient(135deg,#00e5ff,#7c4dff);border:none;color:#fff;padding:11px 26px;border-radius:22px;font-size:14px;cursor:pointer;">复制链接</button>';
  document.body.appendChild(g);
  document.getElementById("dsh-wx-copy").onclick = function () {
    try {
      var ta = document.createElement("textarea");
      ta.value = url;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      var b = document.getElementById("dsh-wx-copy");
      b.textContent = "✅ 已复制";
      setTimeout(function () { b.textContent = "复制链接"; }, 2000);
    } catch (e) {}
  };
})();